Release script colorizes errors

diff --git a/bin/release b/bin/release
--- a/bin/release
+++ b/bin/release
@@ -1,5 +1,9 @@
 #!/usr/bin/env sh
 
+BOLD='\033[1m'
+RED='\033[31m'
+RESET='\033[0m'
+
 get_arch() {
   echo "$(uname -p)"
 }
@@ -28,15 +32,15 @@ EOF
 
 validate_env() {
   if [ -z "${AWS_ACCESS_KEY_ID}" ]; then
-    echo "Error! Missing env: AWS_ACCESS_KEY_ID" >&2
+    printf "${RED}Error! Missing env: ${BOLD}AWS_ACCESS_KEY_ID${RESET}\n" >&2
     return 1
   fi
   if [ -z "${AWS_SECRET_ACCESS_KEY}" ]; then
-    echo "Error! Missing env: AWS_SECRET_ACCESS_KEY" >&2
+    printf "${RED}Error! Missing env: ${BOLD}AWS_SECRET_ACCESS_KEY${RESET}\n" >&2
     return 1
   fi
   if [ -z "${AWS_DEFAULT_REGION}" ]; then
-    echo "Error! Missing env: AWS_DEFAULT_REGION" >&2
+    printf "${RED}Error! Missing env: ${BOLD}AWS_DEFAULT_REGION${RESET}\n" >&2
     return 1
   fi
 }
